AWSTemplateFormatVersion: '2010-09-09'
Description: >
  File Integrity Monitoring solution using AWS Systems Manager Inventory to collect
  file metadata from EC2 instances and detect unauthorized file changes.

# ------------------------------------------------------------------------
# Parameters
# ------------------------------------------------------------------------
Parameters:
  DeploymentBucketName:
    Type: String
    Description: Name of the S3 bucket where Lambda code and layer packages are stored

  InventorySchedule:
    Type: String
    Default: "rate(30 minutes)"
    Description: Schedule expression for SSM Inventory collection (e.g., rate(30 minutes), cron(0 */6 * * ? *))

  MonitoredPath:
    Type: String
    Default: "/etc/paymentapp/"
    Description: File system path to monitor for changes (e.g., /etc/paymentapp/, /etc/)

  CriticalFilePatterns:
    Type: String
    Default: "^/etc/paymentapp/config.*$"
    Description: Comma-separated regex patterns for critical files to monitor

  FindingSeverity:
    Type: String
    Default: "MEDIUM"
    Description: Severity level for Security Hub findings

  InventoryTagKey:
    Type: String
    Default: "FIM-Enabled"
    Description: Tag key to identify EC2 instances for inventory collection

  InventoryTagValue:
    Type: String
    Default: "true"
    Description: Tag value to identify EC2 instances for inventory collection

# ------------------------------------------------------------------------
# Resources
# ------------------------------------------------------------------------
Resources:
  # S3 bucket for access logs (must be created first)
  # Note: This is the central logging bucket and does not have its own LoggingConfiguration
  # because S3 does not support self-logging (a bucket cannot log to itself).
  # Access to this bucket is protected by versioning, Object Lock, encryption, and CloudTrail.
  LoggingBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "fim-logs-${AWS::AccountId}-${AWS::Region}"
      AccessControl: Private
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerPreferred
      VersioningConfiguration:
        Status: Enabled
      ObjectLockEnabled: true
      ObjectLockConfiguration:
        ObjectLockEnabled: Enabled
        Rule:
          DefaultRetention:
            Mode: GOVERNANCE
            Days: 90
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  # Bucket policy for LoggingBucket to allow S3 log delivery
  LoggingBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref LoggingBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: S3ServerAccessLogsPolicy
            Effect: Allow
            Principal:
              Service: logging.s3.amazonaws.com
            Action: s3:PutObject
            Resource: !Sub "${LoggingBucket.Arn}/*"
            Condition:
              StringEquals:
                aws:SourceAccount: !Ref AWS::AccountId
          - Sid: EnforceTLS
            Effect: Deny
            Principal: "*"
            Action: s3:*
            Resource:
              - !GetAtt LoggingBucket.Arn
              - !Sub "${LoggingBucket.Arn}/*"
            Condition:
              Bool:
                aws:SecureTransport: false

  # Allow S3 bucket to invoke the Lambda function
  S3InvokeLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref FimChangeDetectorFunction
      Action: lambda:InvokeFunction
      Principal: s3.amazonaws.com
      SourceAccount: !Ref AWS::AccountId
      SourceArn: !Sub "arn:aws:s3:::fim-inventory-${AWS::AccountId}-${AWS::Region}"

  # S3 bucket to store Systems Manager Inventory snapshots
  InventoryBucket:
    Type: AWS::S3::Bucket
    DependsOn: 
      - LoggingBucket
      - S3InvokeLambdaPermission
    Properties:
      BucketName: !Sub "fim-inventory-${AWS::AccountId}-${AWS::Region}"
      AccessControl: Private
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      # Enable access logging for auditing
      LoggingConfiguration:
        DestinationBucketName: !Ref LoggingBucket
        LogFilePrefix: "access-logs/"
      # Enforce private access and block any public exposure
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      # Native event notification to trigger Lambda
      NotificationConfiguration:
        LambdaConfigurations:
          - Event: s3:ObjectCreated:Put
            Filter:
              S3Key:
                Rules:
                  - Name: prefix
                    Value: "AWS%3AFile/"
            Function: !GetAtt FimChangeDetectorFunction.Arn

  # S3 bucket policy for SSM Resource Data Sync delivery
  InventoryBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref InventoryBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: SSMBucketPermissionsCheck
            Effect: Allow
            Principal:
              Service: ssm.amazonaws.com
            Action: s3:GetBucketAcl
            Resource: !GetAtt InventoryBucket.Arn
          - Sid: SSMBucketDelivery
            Effect: Allow
            Principal:
              Service: ssm.amazonaws.com
            Action: s3:PutObject
            Resource: !Sub "${InventoryBucket.Arn}/*"
            Condition:
              StringEquals:
                s3:x-amz-acl: bucket-owner-full-control
                aws:SourceAccount: !Ref AWS::AccountId
          - Sid: SSMBucketDeliveryArnCheck
            Effect: Allow
            Principal:
              Service: ssm.amazonaws.com
            Action: s3:PutObject
            Resource: !Sub "${InventoryBucket.Arn}/*"
            Condition:
              ArnLike:
                aws:SourceArn: !Sub "arn:aws:ssm:*:${AWS::AccountId}:resource-data-sync/*"
          # Enforce HTTPS access only
          - Sid: EnforceTLS
            Effect: Deny
            Principal: "*"
            Action: s3:*
            Resource:
              - !GetAtt InventoryBucket.Arn
              - !Sub "${InventoryBucket.Arn}/*"
            Condition:
              Bool:
                aws:SecureTransport: false

  # SSM Resource Data Sync to export inventory data to S3
  InventoryResourceDataSync:
    Type: AWS::SSM::ResourceDataSync
    DependsOn: InventoryBucketPolicy
    Properties:
      SyncName: !Sub "${AWS::StackName}-inventory-sync"
      S3Destination:
        BucketName: !Ref InventoryBucket
        BucketRegion: !Ref AWS::Region
        SyncFormat: JsonSerDe

  # SSM Inventory Association to collect file metadata
  InventoryAssociation:
    Type: AWS::SSM::Association
    Properties:
      Name: AWS-GatherSoftwareInventory
      AssociationName: !Sub "${AWS::StackName}-file-inventory"
      ScheduleExpression: !Ref InventorySchedule
      Targets:
        - Key: !Sub "tag:${InventoryTagKey}"
          Values:
            - !Ref InventoryTagValue
      Parameters:
        applications: [Disabled]
        awsComponents: [Disabled]
        customInventory: [Disabled]
        files:
          - !Sub |
            [{"Path":"${MonitoredPath}","Pattern":["*"],"Recursive":true}]
        instanceDetailedInformation: [Disabled]
        networkConfig: [Disabled]
        services: [Disabled]
        windowsRegistry: [Disabled]
        windowsRoles: [Disabled]
        windowsUpdates: [Disabled]

  # Dead Letter Queue for failed Lambda invocations
  FimChangeDetectorDLQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub "${AWS::StackName}-fim-dlq"
      MessageRetentionPeriod: 1209600  # 14 days
      KmsMasterKeyId: alias/aws/sqs

  # Managed IAM Policy for FIM Lambda function
  FimChangeDetectorManagedPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: Managed policy for FIM Lambda function to access S3, Security Hub, and SQS
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action: securityhub:BatchImportFindings
            Resource: !Sub "arn:aws:securityhub:${AWS::Region}:${AWS::AccountId}:product/${AWS::AccountId}/default"
          - Effect: Allow
            Action:
              - s3:GetObject
              - s3:GetObjectVersion
              - s3:ListBucketVersions
              - s3:DeleteObjectVersion
            Resource:
              - !Sub "arn:aws:s3:::fim-inventory-${AWS::AccountId}-${AWS::Region}"
              - !Sub "arn:aws:s3:::fim-inventory-${AWS::AccountId}-${AWS::Region}/*"
          - Effect: Allow
            Action: sqs:SendMessage
            Resource: !GetAtt FimChangeDetectorDLQ.Arn

  # IAM Role for the Lambda function that detects file changes
  FimChangeDetectorRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - !Ref FimChangeDetectorManagedPolicy

  # Lambda layer with helper functions for FIM logic
  FimChangeDetectorLayer:
    Type: AWS::Lambda::LayerVersion
    Properties:
      LayerName: fim-change-detector-helpers
      Description: Helper functions for File Integrity Monitoring
      CompatibleRuntimes:
        - python3.12
        - python3.11
      Content:
        S3Bucket: !Ref DeploymentBucketName
        S3Key: layer/helpers_layer.zip

  # Lambda function to detect file changes and send findings
  FimChangeDetectorFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: fim-change-detector
      Description: Detects file changes by comparing SSM Inventory versions and creates Security Hub findings
      Runtime: python3.12
      Role: !GetAtt FimChangeDetectorRole.Arn
      Handler: lambda_function.lambda_handler
      Timeout: 120
      MemorySize: 256
      ReservedConcurrentExecutions: 10  # Limit concurrency to cap blast-radius and cost
      Code:
        S3Bucket: !Ref DeploymentBucketName
        S3Key: lambda/fim-change-detector.zip
      Layers:
        - !Ref FimChangeDetectorLayer
      DeadLetterConfig:
        TargetArn: !GetAtt FimChangeDetectorDLQ.Arn
      Environment:
        Variables:
          CRITICAL_FILE_PATTERNS: !Ref CriticalFilePatterns
          SEVERITY_LABEL: !Ref FindingSeverity

# ------------------------------------------------------------------------
# Outputs
# ------------------------------------------------------------------------
Outputs:
  LoggingBucketName:
    Description: S3 bucket for access logs with versioning and Object Lock
    Value: !Ref LoggingBucket

  InventoryBucketName:
    Description: S3 bucket where SSM Inventory data is stored
    Value: !Ref InventoryBucket

  ResourceDataSyncName:
    Description: Name of the SSM Resource Data Sync
    Value: !Ref InventoryResourceDataSync

  InventoryAssociationId:
    Description: ID of the SSM Inventory Association
    Value: !Ref InventoryAssociation

  LambdaFunctionName:
    Description: Name of the Lambda function for file integrity monitoring
    Value: !Ref FimChangeDetectorFunction

  LambdaFunctionArn:
    Description: ARN of the Lambda function
    Value: !GetAtt FimChangeDetectorFunction.Arn

  LayerVersionArn:
    Description: ARN of the Lambda Layer with helper functions
    Value: !Ref FimChangeDetectorLayer

  DeadLetterQueueUrl:
    Description: URL of the Dead Letter Queue for failed Lambda invocations
    Value: !Ref FimChangeDetectorDLQ

  DeadLetterQueueArn:
    Description: ARN of the Dead Letter Queue
    Value: !GetAtt FimChangeDetectorDLQ.Arn

  DeploymentRegion:
    Description: AWS Region where the solution is deployed
    Value: !Ref AWS::Region