AWSTemplateFormatVersion: '2010-09-09'
Description: >
  File Integrity Monitoring solution using AWS Systems Manager Inventory to collect 
  file metadata from EC2 instances.a

Parameters:
  DeploymentBucketName:
    Type: String
    Description: Name of the S3 bucket where Lambda code and layer packages are stored
  
  InventorySchedule:
    Type: String
    Default: "rate(30 minutes)"
    Description: Schedule expression for SSM Inventory collection (e.g., rate(30 minutes), cron(0 */6 * * ? *))
  
  MonitoredPath:
    Type: String
    Default: "/etc/paymentapp/"
    Description: File system path to monitor for changes (e.g., /etc/paymentapp/, /etc/)
  
  CriticalFilePatterns:
    Type: String
    Default: "^/etc/paymentapp/config.*$"
    Description: Comma-separated regex patterns for critical files to monitor (e.g., ^/etc/paymentapp/config.*$,^/etc/passwd$)
  
  FindingSeverity:
    Type: String
    Default: "MEDIUM"
    Description: Severity level for Security Hub findings

Resources:
  # S3 Bucket for SSM Inventory Data
  InventoryBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "inventorymonitorfim-${AWS::AccountId}-${AWS::Region}"
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  InventoryBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref InventoryBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: SSMBucketPermissionsCheck
            Effect: Allow
            Principal:
              Service: ssm.amazonaws.com
            Action: s3:GetBucketAcl
            Resource: !GetAtt InventoryBucket.Arn
          - Sid: SSMBucketDelivery
            Effect: Allow
            Principal:
              Service: ssm.amazonaws.com
            Action: s3:PutObject
            Resource: !Sub "${InventoryBucket.Arn}/*"
            Condition:
              StringEquals:
                s3:x-amz-acl: bucket-owner-full-control
                aws:SourceAccount: !Ref AWS::AccountId
              ArnLike:
                aws:SourceArn: !Sub "arn:aws:ssm:*:${AWS::AccountId}:resource-data-sync/*"

  # SSM Resource Data Sync
  InventoryResourceDataSync:
    Type: AWS::SSM::ResourceDataSync
    DependsOn: InventoryBucketPolicy
    Properties:
      SyncName: !Sub "${AWS::StackName}-inventory-sync"
      S3Destination:
        BucketName: !Ref InventoryBucket
        BucketRegion: !Ref AWS::Region
        SyncFormat: JsonSerDe

  # SSM Inventory Association
  InventoryAssociation:
    Type: AWS::SSM::Association
    Properties:
      Name: AWS-GatherSoftwareInventory
      AssociationName: !Sub "${AWS::StackName}-file-inventory"
      ScheduleExpression: !Ref InventorySchedule
      Targets:
        - Key: InstanceIds
          Values:
            - "*"
      Parameters:
        applications:
          - Disabled
        awsComponents:
          - Disabled
        customInventory:
          - Disabled
        files:
          - !Sub |
            [{"Path":"${MonitoredPath}","Pattern":["*"],"Recursive":true}]
        instanceDetailedInformation:
          - Disabled
        networkConfig:
          - Disabled
        services:
          - Disabled
        windowsRegistry:
          - Disabled
        windowsRoles:
          - Disabled
        windowsUpdates:
          - Disabled

  FimChangeDetectorRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: FimChangeDetectorPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: securityhub:BatchImportFindings
                Resource: "*"
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:GetObjectVersion
                  - s3:ListBucketVersions
                  - s3:DeleteObjectVersion
                Resource:
                  - !GetAtt InventoryBucket.Arn
                  - !Sub "${InventoryBucket.Arn}/*"

  FimChangeDetectorLayer:
    Type: AWS::Lambda::LayerVersion
    Properties:
      LayerName: fim-change-detector-helpers
      Description: Helper functions for File Integrity Monitoring
      CompatibleRuntimes:
        - python3.13
        - python3.12
      Content:
        S3Bucket: !Ref DeploymentBucketName
        S3Key: layer/helpers_layer.zip

  FimChangeDetectorFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: fim-change-detector
      Description: Detects file changes by comparing SSM Inventory versions and creates Security Hub findings
      Runtime: python3.13
      Role: !GetAtt FimChangeDetectorRole.Arn
      Handler: lambda_function.lambda_handler
      Timeout: 60
      MemorySize: 256
      Code:
        S3Bucket: !Ref DeploymentBucketName
        S3Key: lambda/fim-change-detector.zip
      Layers:
        - !Ref FimChangeDetectorLayer
      Environment:
        Variables:
          CRITICAL_FILE_PATTERNS: !Ref CriticalFilePatterns
          SEVERITY_LABEL: !Ref FindingSeverity

  S3InvokeLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref FimChangeDetectorFunction
      Action: lambda:InvokeFunction
      Principal: s3.amazonaws.com
      SourceAccount: !Ref AWS::AccountId
      SourceArn: !Sub "arn:aws:s3:::inventorymonitorfim-${AWS::AccountId}-${AWS::Region}"

  ConfigureS3NotificationRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: S3NotificationPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:PutBucketNotification
                  - s3:GetBucketNotification
                Resource: !GetAtt InventoryBucket.Arn

  ConfigureS3NotificationFunction:
    Type: AWS::Lambda::Function
    Properties:
      Runtime: python3.13
      Handler: configure_s3_notification.handler
      Role: !GetAtt ConfigureS3NotificationRole.Arn
      Timeout: 60
      Code:
        S3Bucket: !Ref DeploymentBucketName
        S3Key: lambda/configure-s3-notification.zip

  ConfigureS3Notification:
    Type: Custom::S3Notification
    DependsOn:
      - S3InvokeLambdaPermission
      - ConfigureS3NotificationFunction
    Properties:
      ServiceToken: !GetAtt ConfigureS3NotificationFunction.Arn
      Bucket: !Ref InventoryBucket
      LambdaArn: !GetAtt FimChangeDetectorFunction.Arn

Outputs:
  InventoryBucketName:
    Description: S3 bucket where SSM Inventory data is stored
    Value: !Ref InventoryBucket
    Export:
      Name: !Sub "${AWS::StackName}-InventoryBucket"
  
  ResourceDataSyncName:
    Description: Name of the SSM Resource Data Sync
    Value: !Ref InventoryResourceDataSync
    Export:
      Name: !Sub "${AWS::StackName}-DataSync"
  
  InventoryAssociationId:
    Description: ID of the SSM Inventory Association
    Value: !Ref InventoryAssociation
    Export:
      Name: !Sub "${AWS::StackName}-Association"
  
  LambdaFunctionName:
    Description: Name of the Lambda function for file integrity monitoring
    Value: !Ref FimChangeDetectorFunction
    Export:
      Name: !Sub "${AWS::StackName}-FunctionName"
  
  LambdaFunctionArn:
    Description: ARN of the Lambda function
    Value: !GetAtt FimChangeDetectorFunction.Arn
    Export:
      Name: !Sub "${AWS::StackName}-FunctionArn"
  
  LayerVersionArn:
    Description: ARN of the Lambda Layer with helper functions
    Value: !Ref FimChangeDetectorLayer
    Export:
      Name: !Sub "${AWS::StackName}-LayerArn"
  
  DeploymentRegion:
    Description: AWS Region where the solution is deployed
    Value: !Ref AWS::Region
